<a href="https://colab.research.google.com/github/geekynadir/semester-8/blob/main/week7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("/content/sample_data/california_housing_test.csv")
df.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [ ]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

question 2

In [ ]:
avrg=df["total_rooms"].median()
avrg

2106.0

In [ ]:
subset = df.iloc[:5, [2, 3]]
average = subset.mean()
average

housing_median_age      28.8
total_rooms           2058.4
dtype: float64

In [ ]:
s=df.sum(axis=1)
s

0       351337.9285
1       179368.5590
2       276523.7634
3       330091.5959
4        84210.5975
           ...
2995    228895.7390
2996    248017.3106
2997     63998.8895
2998    162630.2508
2999    503007.3508
Length: 3000, dtype: float64

In [ ]:
maxm=df.max(axis=0)
maxm

longitude               -114.4900
latitude                  41.9200
housing_median_age        52.0000
total_rooms            30450.0000
total_bedrooms          5419.0000
population             11935.0000
households              4930.0000
median_income             15.0001
median_house_value    500001.0000
dtype: float64

Week 8

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
df.column=[
    'Median_Income', 'House_Age', 'Avg_Rooms',
    'Avg_Bedrooms', 'Population', 'Avg_Occupancy',
    'Latitude', 'Longitude'
]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

/tmp/ipykernel_3879/2283984688.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.column=[

In [ ]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [ ]:
df['population'] = df['population'].astype(int)

df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population              int64
households            float64
median_income         float64
median_house_value    float64
dtype: object

questiuon 2

In [ ]:
df_filtered = df[df['population'] < 50]
df_filtered

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
3,-118.36,33.82,28.0,67.0,15.0,49,11.0,6.1359,330000.0
676,-118.25,34.09,52.0,104.0,20.0,32,17.0,3.7500,241700.0
740,-117.12,32.66,52.0,16.0,4.0,8,3.0,1.1250,60000.0
742,-122.22,37.88,20.0,95.0,13.0,31,15.0,2.4444,475000.0
842,-117.95,35.08,1.0,83.0,15.0,32,15.0,4.8750,141700.0
894,-122.39,37.74,52.0,126.0,24.0,37,27.0,10.2264,225000.0
1050,-121.96,37.74,2.0,200.0,20.0,25,9.0,15.0001,350000.0
1094,-120.33,39.30,16.0,868.0,178.0,44,21.0,3.0000,175000.0
1115,-116.95,33.86,1.0,6.0,2.0,8,2.0,1.6250,55000.0
1345,-121.29,37.33,36.0,48.0,12.0,27,8.0,4.0000,75000.0
1355,-117.11,32.66,52.0,25.0,5.0,14,9.0,1.6250,118800.0
1356,-121.90,37.39,42.0,42.0,14.0,26,14.0,1.7361,500001.0
1408,-123.35,40.99,23.0,141.0,59.0,47,23.0,1.1250,66000.0
1509,-119.02,35.38,52.0,90.0,35.0,36,31.0,0.8054,60000.0
1726,-117.05,33.03,16.0,87.0,20.0,32,21.0,4.3571,144600.0
2132,-121.84,36.62,26.0,32.0,8.0,27,10.0,2.2250,150000.0
2213,-121.78,40.12,14.0,388.0,108.0,35,17.0,6.1359,106300.0
2494,-118.44,34.04,49.0,32.0,7.0,14,7.0,2.1875,225000.0
2502,-118.23,33.76,21.0,49.0,14.0,29,16.0,5.0000,87500.0
2636,-120.92,37.63,39.0,45.0,8.0,22,9.0,1.7679,450000.0
2640,-114.62,33.62,26.0,18.0,3.0,5,3.0,0.5360,275000.0
2690,-118.06,34.03,36.0,21.0,7.0,21,9.0,2.3750,175000.0
2768,-122.49,38.00,26.0,48.0,8.0,19,8.0,7.7197,400000.0
2844,-117.09,34.01,37.0,106.0,18.0,27,12.0,4.0556,131300.0
2879,-121.84,38.02,46.0,66.0,22.0,37,21.0,0.5360,87500.0
2998,-117.12,34.10,40.0,96.0,14.0,46,14.0,3.2708,162500.0